### PR TITLE
- added support for loading credentials from ECS

### PR DESCRIPTION
**Pull request by theburningmonk**
as per described in #2

### CODE REVIEW

**Comment by SaMnCo** [comment]
+1, interested in getting this merged. Thanks.

**Comment by rshurts** [comment]
👍 ECS support would be great.

**Comment by mhart** [comment]
Ugh, so sorry it took me so long to merge this! This is great, thanks @theburningmonk – will publish a new release ASAP

**Comment by mhart** [comment]
Published as v1.3.0 – will update README in a sec

**Comment by mhart** [comment]
Actually cleaned things up a little and published a new version, v1.4.0

Will now pick which http call to make (EC2 or ECS) depending on env – instead of making both calls.

**Comment by theburningmonk** [comment]
Thanks @mhart much appreciated! 👍

**Pull request merged**
